### ISSUE TITLE
better documentation of readme file ;

### ISSUE THREAD

**Issue by tigercoding56** [pygame-web/python-wasm-sdk#9]
how do i build python for wasm?

**Comment by tigercoding56** [comment]
(i am to stupid to figure build.yaml files out )

**Comment by pmp-p** [comment]
The point of providing a sdk is to not have to explain how to do it.

There are MANY ways to build python for wasm and not all will fit your use case. This SDK is game oriented [^1]. and geared toward maximum compatibility with old or mobile hardware.

Default guide is there https://github.com/python/cpython/tree/main/Tools/wasm but it may not cover all that this build can do YMMV.

[^1]: it is used "as is" in pygame-ce continuous integration

**Comment by tigercoding56** [comment]
> The point of providing a sdk is to not have to explain how to do it.
> 
> There are MANY ways to build python for wasm and not all will fit your use case. This SDK is game oriented [1](#user-content-fn-1-b6bcda8ddeb5ef75e1369fbed15f5d07). and geared toward maximum compatibility with old or mobile hardware.
> 
> Default guide is there [python/cpython@`main`/Tools/wasm](https://github.com/python/cpython/tree/main/Tools/wasm?rgh-link-date=2023-09-10T18%3A57%3A03Z) but it may not cover all that this build can do YMMV.
> ## Footnotes
> 
>     1. it is used "as is" in pygame-ce continuous integration [↩](#user-content-fnref-1-b6bcda8ddeb5ef75e1369fbed15f5d07)

thank you , sorry i am to stupid to figure out this is a SDK
